version: '3.1'

services:

  postgres:
    image: postgres:13-alpine

    ports:

      - '3306:3306'
    volumes:

      - ./data:/var/lib/postgres

    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=mysecretpassword